order:
  - Definition
  - Properties
  - Permutations Formula
  - Permutations II
  - Cramer's Rule
  - Recurrent Formula and Cofactors
  - Determinant Computation Algorithm
  - Jacobian Matrix and Its Determinant
  - Reflection Matrix
